/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement;
import com.microsoft.sqlserver.jdbc.SQLServerResultSet;
import dao.accountManagerDAO;
import database.JDBCUtil;
import static java.lang.System.exit;
import java.sql.Connection;
import javax.security.auth.login.AppConfigurationEntry;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import model.accountManager;
import model.nhanVien;
import model.shareData;
import model.shareMain;

public class frmMain extends javax.swing.JFrame {

    private frmTTsach mTTsach;
    private frmAccount mAccount;
    private frmNhanVien mNhanVien;
    private frmNhaCC mNhaCC;
    private frmPhieuNhap mPhieuNhap;
    private frmPhieuXuat mPhieuXuat;
    public static frmQuenMatKhau fqmk;

    public frmMain() {
        initComponents();
        this.setLocationRelativeTo(null);
        fqmk = new frmQuenMatKhau(this, rootPaneCheckingEnabled);

//          if((new accountManagerDAO().getList()).size() == 0){
//          nhanVien nv = new nhanVien("111","Đặng Quốc Thuận","Nam","Manager","Long An");
//          
//          accountManager ac = new accountManager("2003","2003","Manager","111");
//          if(new accountManagerDAO().insert2(ac)){
//              return ;
//          }
//          }
        frmDangNhap f = new frmDangNhap(this, true);
        f.setVisible(true);

        loginSuccess();
    }
    int n = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnnhap = new javax.swing.JButton();
        btnxuat = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButton7 = new javax.swing.JButton();
        jtbmain = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtrole = new javax.swing.JLabel();
        txtid = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        mnuclose = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        btnnv = new javax.swing.JMenuItem();
        btnaccount = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar1.setRollover(true);
        jToolBar1.setAutoscrolls(true);
        jToolBar1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jToolBar1.setDoubleBuffered(true);
        jToolBar1.setFocusCycleRoot(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/book_books_school_read_icon_210070.png"))); // NOI18N
        jButton1.setText("TT sách");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/admin_person_user_man_2839.png"))); // NOI18N
        jButton2.setText("Nhà CC");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);
        jToolBar1.add(jSeparator1);

        btnnhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/note.png"))); // NOI18N
        btnnhap.setText("Phiếu nhập");
        btnnhap.setFocusable(false);
        btnnhap.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnnhap.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnhapActionPerformed(evt);
            }
        });
        jToolBar1.add(btnnhap);

        btnxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pencil.png"))); // NOI18N
        btnxuat.setText("Phiếu xuất");
        btnxuat.setFocusable(false);
        btnxuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnxuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxuatActionPerformed(evt);
            }
        });
        jToolBar1.add(btnxuat);
        jToolBar1.add(jSeparator2);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/1.png"))); // NOI18N
        jButton7.setText("In");
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton7);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Role:");

        txtid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtid.setForeground(new java.awt.Color(0, 102, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtrole, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(txtid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtrole))
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(228, 224, 224));

        jMenu3.setText("Hệ thống");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout-icon-16.png"))); // NOI18N
        jMenuItem4.setText("Đăng xuất");
        jMenuItem4.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jMenuItem4ComponentShown(evt);
            }
        });
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        mnuclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Actions-edit-delete-icon-16.png"))); // NOI18N
        mnuclose.setText("Thoát");
        mnuclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnucloseActionPerformed(evt);
            }
        });
        jMenu3.add(mnuclose);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Quản lý");

        btnnv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Person-Male-Light-icon-16.png"))); // NOI18N
        btnnv.setText("Nhân viên");
        btnnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnvActionPerformed(evt);
            }
        });
        jMenu1.add(btnnv);

        btnaccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Apps-preferences-desktop-user-password-icon-16.png"))); // NOI18N
        btnaccount.setText("Account");
        btnaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaccountActionPerformed(evt);
            }
        });
        jMenu1.add(btnaccount);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("About me");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jtbmain)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtbmain, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnucloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnucloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnucloseActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (mNhaCC == null) {
            mNhaCC = new frmNhaCC();
            ImageIcon icon = new ImageIcon(getClass().getResource("/icons/10207-man-student-light-skin-tone-icon-16.png"));
            jtbmain.addTab("Nhà cung cấp", icon, mNhaCC, "Nhà cung cấp");
        }
        jtbmain.setSelectedComponent(mNhaCC);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (mTTsach == null) {
            mTTsach = new frmTTsach();
            ImageIcon icon = new ImageIcon(getClass().getResource("/icons/10207-man-student-light-skin-tone-icon-16.png"));
            jtbmain.addTab("Thông tin sách", icon, mTTsach, "Thông tin sách");
        }
//        else {
//             mTTsach = new frmTTsach();
//            ImageIcon icon = new ImageIcon(getClass().getResource("/icons/10207-man-student-light-skin-tone-icon-16.png"));
//            jtbmain.addTab("Thông tin sách",icon,mTTsach,"Thông tin sách");
//        }
        jtbmain.setSelectedComponent(mTTsach);
//        jtbmain.setSelectedComponent(mTTsach);
        n = 1;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaccountActionPerformed
        if (mAccount == null) {
            mAccount = new frmAccount();
            ImageIcon icon = new ImageIcon(getClass().getResource("/icons/Person-Male-Light-icon-16.png"));
            jtbmain.addTab("Account", icon, mAccount, "Account");
        }

        jtbmain.setSelectedComponent(mAccount);

    }//GEN-LAST:event_btnaccountActionPerformed

    private void btnnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnvActionPerformed
        if (mNhanVien == null) {
            mNhanVien = new frmNhanVien();
            ImageIcon icon = new ImageIcon(getClass().getResource("/icons/Person-Male-Light-icon-16.png"));
            jtbmain.addTab("Nhân Viên", icon, mNhanVien, "Nhân Viên");
        }
        jtbmain.setSelectedComponent(mNhanVien);
    }//GEN-LAST:event_btnnvActionPerformed

    private void btnnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnhapActionPerformed
        if (mPhieuNhap == null) {
            mPhieuNhap = new frmPhieuNhap();
            ImageIcon icon = new ImageIcon(getClass().getResource("/icons/Person-Male-Light-icon-16.png"));
            jtbmain.addTab("Phiếu nhập", icon, mPhieuNhap, "Phiếu Nhập");
        }

        jtbmain.setSelectedComponent(mPhieuNhap);


    }//GEN-LAST:event_btnnhapActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        dispose();
        frmDangNhap f = new frmDangNhap(this, true);
        f.setVisible(true);
        if (shareMain.main == true) {
            this.setVisible(true);
            loginSuccess();
            jtbmain.removeAll();
            mTTsach = null;
            mPhieuNhap = null;
            mPhieuXuat = null;
            mAccount = null;
            mNhaCC = null;
            mNhanVien = null;

        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem4ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jMenuItem4ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ComponentShown

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed

    }//GEN-LAST:event_jMenu3ActionPerformed

    private void btnxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxuatActionPerformed
        if (mPhieuXuat == null) {
            mPhieuXuat = new frmPhieuXuat();
            ImageIcon icon = new ImageIcon(getClass().getResource("/icons/Person-Male-Light-icon-16.png"));
            jtbmain.addTab("Phiếu xuất", icon, mPhieuXuat, "Phiếu xuất");
        }
        jtbmain.setSelectedComponent(mPhieuXuat);

    }//GEN-LAST:event_btnxuatActionPerformed

    private void loginSuccess() {

        nhanVien nv = new nhanVien();

        try {
            Connection c = JDBCUtil.getConnection();
            String sql = "select tenNV"
                    + " from accountManager join nhanVien on accountManager.maNV=nhanVien.maNV"
                    + " where username=?";
            SQLServerPreparedStatement ps = (SQLServerPreparedStatement) c.prepareStatement(sql);
            ps.setString(1, shareData.account.getTenDangNhap());
            SQLServerResultSet rs = (SQLServerResultSet) ps.executeQuery();
            if (rs.next()) {

                nv.setTenNhanVien(rs.getString("tenNV"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        txtid.setText(nv.getTenNhanVien());
        txtrole.setText(shareData.account.getRole());

        if (shareData.account.getRole().equals("Employee_A")) {
            btnaccount.setEnabled(false);
            btnxuat.setEnabled(false);
            btnnhap.setEnabled(true);
            btnnv.setEnabled(false);

        } else if (shareData.account.getRole().equals("Manager")) {
            btnaccount.setEnabled(true);
            btnxuat.setEnabled(true);
            btnnhap.setEnabled(true);
            btnnv.setEnabled(true);
        } else {
            btnaccount.setEnabled(false);
            btnxuat.setEnabled(true);
            btnnhap.setEnabled(false);
            btnnv.setEnabled(false);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnaccount;
    private javax.swing.JButton btnnhap;
    private javax.swing.JMenuItem btnnv;
    private javax.swing.JButton btnxuat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTabbedPane jtbmain;
    private javax.swing.JMenuItem mnuclose;
    private javax.swing.JLabel txtid;
    private javax.swing.JLabel txtrole;
    // End of variables declaration//GEN-END:variables
}
