/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;


import com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement;
import com.microsoft.sqlserver.jdbc.SQLServerResultSet;
import dao.accountManagerDAO;
import dao.nhanVienDAO;
import database.JDBCUtil;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.accountManager;
import model.nhanVien;
import model.shareData;



public class frmNhanVien extends javax.swing.JPanel {
 private ArrayList<nhanVien> list = new nhanVienDAO().getList();
     DefaultTableModel model; 
     private int selectedIndex;
     public frmNhanVien() {
        initComponents();
//        
//        model = (DefaultTableModel) table_nhanvien.getModel();
//        
//        model.setColumnIdentifiers(new Object[]{
//            "STT", "Mã nhân viên", "Tên nhân viên", "Giới tính", "Chức vụ", "Địa chỉ"
//        });
        loadArray();
        
    }
//     int i = 1;
//     public void showTable(){
//         for(nhanVien nv : list) {
//	        model.addRow(new Object[]{
//	            i++, nv.getMaNhanVien(), nv.getTenNhanVien(),nv.getGioiTinh(), nv.getChucVu(), nv.getDiaChi()
//	        });
//    }
//}
      
    int i = 1;
    public void loadArray(){
        model = (DefaultTableModel) table_nhanvien.getModel();
        model.setRowCount(0);
         for(nhanVien nv : list) {
	        model.addRow(new Object[]{
	            i++,nv.getMaNhanVien(),nv.getTenNhanVien(),nv.getGioiTinh(),nv.getChucVu(),nv.getDiaChi()
	        });
    }
         
    }
    
      public void xoatrang(){
     
       txtmanv.setText("");
       txttennv.setText("");
          txtdiachi.setText("");
//    rdom.setSelected(false);
//       rdoe.setSelected(false);
//           rdonam.setSelected(false);
//                rdonu.setSelected(false);
        txtmanv.setEditable(true);
        list = new nhanVienDAO().getList();
        i = 1;
        loadArray();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jTextField1 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        ggg = new javax.swing.JScrollPane();
        table_nhanvien = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtmanv = new javax.swing.JTextField();
        txttennv = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtdiachi = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        rdonam = new javax.swing.JRadioButton();
        rdonu = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        rdom = new javax.swing.JRadioButton();
        rdoe = new javax.swing.JRadioButton();
        rdoeb = new javax.swing.JRadioButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jTextField1.setText("jTextField1");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconfinder-8-avatar-2754583_120515.png"))); // NOI18N
        jLabel1.setText("NHÂN VIÊN");

        table_nhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã nhân viên", "Tên nhân viên", "Giới tính", "Chức Vụ", "Địa chỉ"
            }
        ));
        table_nhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_nhanvienMouseClicked(evt);
            }
        });
        ggg.setViewportView(table_nhanvien);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Tên nhân viên:");

        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/business_man_usersearch_thesearch_theclient_2356.png"))); // NOI18N
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnsearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addComponent(btnsearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Mã nhân viên:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Tên nhân viên:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Giới tính:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Địa chỉ:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/business_application_addmale_useradd_insert_add_user_client_2312.png"))); // NOI18N
        jButton1.setText("Thêm");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete_delete_deleteusers_delete_male_user_maleclient_2348.png"))); // NOI18N
        jButton2.setText("Xóa");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/wrench_tools_configuration_setting_settings_icon_189322.png"))); // NOI18N
        jButton3.setText("Sữa");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/recycle (1).png"))); // NOI18N
        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdonam);
        rdonam.setText("Nam");

        buttonGroup1.add(rdonu);
        rdonu.setText("Nữ");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Chức vụ:");

        buttonGroup2.add(rdom);
        rdom.setText("Manager");
        rdom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdomActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdoe);
        rdoe.setText("Employee_A");

        buttonGroup2.add(rdoeb);
        rdoeb.setText("Employee_B");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtmanv)
                            .addComponent(txttennv, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rdonam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdonu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdom)
                    .addComponent(rdoe)
                    .addComponent(rdoeb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtmanv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txttennv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(rdom))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(rdonam)
                                    .addComponent(rdonu)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(rdoe)
                                .addGap(8, 8, 8)
                                .addComponent(rdoeb))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ggg, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ggg, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        if(txtmanv.getText().equals("")||txttennv.getText().equals("")||txtdiachi.getText().equals("")){
              JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin!");
              return;
        }
       if(rdom.isSelected()==false && rdoe.isSelected()==false &&rdoeb.isSelected()==false){
            JOptionPane.showMessageDialog(this, "Vui lòng chọn chức vụ!");
              return;
        }
       if(rdonam.isSelected()==false && rdonu.isSelected()==false){
            JOptionPane.showMessageDialog(this, "Vui lòng chọn giới tính!");
              return;
        }
       nhanVien nv = new nhanVien();
       nv.setMaNhanVien(txtmanv.getText());
       nv.setTenNhanVien(txttennv.getText());
       nv.setDiaChi(txtdiachi.getText());
        String role="";
                if (rdom.isSelected()){
                    role="Manager";
                }
                if(rdoe.isSelected()){
                    role="Employee_A";
                }
                if(rdoeb.isSelected()){
                    role="Employee_B";
                }
                nv.setChucVu(role);  
        String sex;
                if (rdonam.isSelected()){
                    sex = "Nam";
                }else sex = "Nữ";
                
                nv.setGioiTinh(sex);
                
         
                list.add(nv);
                if(new nhanVienDAO().insert2(nv)){
                    JOptionPane.showMessageDialog(this, "Add success!");
                     i = 1;
                     loadArray();
                     txtmanv.setText("");
                     txttennv.setText("");
                     txtdiachi.setText("");
                     rdom.setSelected(false);
                     rdoe.setSelected(false);
                     rdoeb.setSelected(false);
                     rdonam.setSelected(false);
                     rdonu.setSelected(false);
                }else {
                    JOptionPane.showMessageDialog(this, "Mã nhân viên không được trùng nhau!");
   
                }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          if(txtmanv.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Nhập mã nhân viên cần xóa!");
               txtmanv.requestFocus(); return;
        }
         
         nhanVien nv = new nhanVien();
                nv.setMaNhanVien(txtmanv.getText());
            if(new nhanVienDAO().delete2(nv)){
                   JOptionPane.showMessageDialog(this, "Delete success!");
                   
                   //xóa account của những nv này
                     String sql = "select username" +
                                  " from accountManager" +
                                  " where maNV = '"+nv.getMaNhanVien()+"'";
                     try {
                      java.sql.Connection c = JDBCUtil.getConnection();
                      SQLServerPreparedStatement ps = (SQLServerPreparedStatement) c.prepareStatement(sql);
                       SQLServerResultSet rs = (SQLServerResultSet) ps.executeQuery();
                       while(rs.next()){
                           accountManager ac = new accountManager();
                           ac.setTenDangNhap(rs.getString("username"));
                           boolean kt = false;
                           accountManagerDAO acd = new accountManagerDAO();
                           kt = acd.delete2(ac);
                       }
                      
                } catch (Exception e) {
                }
                    list = new nhanVienDAO().getList();
                    i = 1;
                    loadArray(); 
            }
            
            
            
             
             
    }//GEN-LAST:event_jButton2ActionPerformed

    private void table_nhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_nhanvienMouseClicked
         selectedIndex = table_nhanvien.getSelectedRow();
        if(selectedIndex >= 0){
            txtmanv.setText(table_nhanvien.getValueAt(selectedIndex, 1)+"");
            txtmanv.setEditable(false);
            txttennv.setText(table_nhanvien.getValueAt(selectedIndex, 2)+"");
            txtdiachi.setText(table_nhanvien.getValueAt(selectedIndex, 5)+"");

            
            String role = list.get(selectedIndex).getChucVu();
            if(role.equals("Manager")){
                rdom.setSelected(true);
            }else if(role.equals("Employee")){
                rdoe.setSelected(true);
                    }
            else rdoeb.setSelected(true);
            String sex = list.get(selectedIndex).getGioiTinh();
            if(sex.equals("Nam")){
                rdonam.setSelected(true);
            }else if(sex.equals("Nữ")){
                rdonu.setSelected(true);
                    }
            
        }
    }//GEN-LAST:event_table_nhanvienMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       if (txtmanv.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Nhập mã nhân viên để sữa! ");
               txtmanv.requestFocus(); return;
        }
       nhanVien nv = new nhanVien();
      nv.setMaNhanVien(txtmanv.getText());
       nv.setTenNhanVien(txttennv.getText());
       nv.setDiaChi(txtdiachi.getText());
        String role="";
               if (rdom.isSelected()){
                    role="Manager";
                }
                if(rdoe.isSelected()){
                    role="Employee_A";
                }
                if(rdoeb.isSelected()){
                    role="Employee_B";
                }
                nv.setChucVu(role);  
        String sex;
                if (rdonam.isSelected()){
                    sex = "Nam";
                }else sex = "Nữ";
                
                nv.setGioiTinh(sex);
                
        if(new nhanVienDAO().updata2(nv)){
                   JOptionPane.showMessageDialog(this, "Sửa thành công!");
                    list = new nhanVienDAO().getList();
                    i = 1;
                    loadArray(); 
                    txtmanv.setText("");
                     txttennv.setText("");
                     txtdiachi.setText("");
                     rdom.setSelected(false);
                     rdoe.setSelected(false);
                     rdoeb.setSelected(false);
                     rdonam.setSelected(false);
                     rdonu.setSelected(false);
                    
            }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        xoatrang();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void rdomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdomActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
         if(txtsearch.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Nhập tên nhân viên để tìm!");
            return;
       }
         int n = 0;
        ArrayList<nhanVien> list2 = new nhanVienDAO().getList();
       ArrayList<nhanVien> list3 = new ArrayList<>();
       for(nhanVien nv : list2){
           if(nv.getTenNhanVien().toUpperCase().contains(txtsearch.getText().toUpperCase().trim())){
               list3.add(nv);
               n++;
           }
       }
       if(n==0){
                   JOptionPane.showMessageDialog(this, "Không tìm thấy!");
              }
       list.clear();
       list.addAll(list3);
       i = 1;
       loadArray();
       
    }//GEN-LAST:event_btnsearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsearch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JScrollPane ggg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton rdoe;
    private javax.swing.JRadioButton rdoeb;
    private javax.swing.JRadioButton rdom;
    private javax.swing.JRadioButton rdonam;
    private javax.swing.JRadioButton rdonu;
    private javax.swing.JTable table_nhanvien;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txtmanv;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JTextField txttennv;
    // End of variables declaration//GEN-END:variables
}
