/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.nhaCCDAO;
import dao.phieuXuatDAO;
import dao.sachGiaoKhoaDAO;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.nhaCC;
import model.phieuXuat;
import model.sachGiaoKhoa;
import model.shareData;

public class frmPhieuXuat extends javax.swing.JPanel {
  private ArrayList<phieuXuat> list = new phieuXuatDAO().getList();
  DefaultTableModel model;
  private int selectedIndex;

  /**
   * Creates new form frmPhieuXuat
   */
  public frmPhieuXuat() {
    initComponents();
    DateFormat df = new SimpleDateFormat("dd-MM-yyyy");
    java.util.Date d = new java.util.Date();
    txtngay.setText(df.format(d));
    txtmanv.setText(shareData.account.getMaNV());
    txtngay.setEditable(false);
    txtmanv.setEditable(false);

    loadArray();

  }

  int i = 1;

  public void loadArray() {
    model = (DefaultTableModel) table_phieuXuat.getModel();
    model.setRowCount(0);
    for (phieuXuat nv : list) {
      model.addRow(new Object[] {
          i++, nv.getMaPX(), nv.getMaNV(), nv.getMaNCC(), nv.getMaSGK(), nv.getNgay(), nv.getSoLuong()
      });
    }

  }

  public void reset() {
    list = new phieuXuatDAO().getList();
    i = 1;
    loadArray();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    txtsoluongxuat = new javax.swing.JLabel();
    txtmapx = new javax.swing.JTextField();
    txtmanv = new javax.swing.JTextField();
    txtsl = new javax.swing.JTextField();
    txtmasach = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    txtngay = new javax.swing.JTextField();
    jLabel8 = new javax.swing.JLabel();
    txtncc = new javax.swing.JTextField();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    table_phieuXuat = new javax.swing.JTable();
    jButton3 = new javax.swing.JButton();
    txtsearch = new javax.swing.JTextField();
    jButton4 = new javax.swing.JButton();

    setBackground(new java.awt.Color(204, 255, 204));
    setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 102), 5, true));

    jPanel1.setBackground(new java.awt.Color(0, 102, 51));
    jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

    jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
    jLabel2.setText("Phiếu Xuất Kho");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(20, Short.MAX_VALUE)));
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap()));

    jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
    jLabel1.setText("Thông tin");

    jPanel2.setBackground(new java.awt.Color(0, 153, 102));

    jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 15)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    jLabel3.setText("• Mã Nhân Viên");

    jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 15)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(255, 255, 255));
    jLabel4.setText("• Mã Phiếu Xuất");

    jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 15)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(255, 255, 255));
    jLabel5.setText("• Mã sách");

    txtsoluongxuat.setFont(new java.awt.Font("Times New Roman", 2, 15)); // NOI18N
    txtsoluongxuat.setForeground(new java.awt.Color(255, 255, 255));
    txtsoluongxuat.setText("• Số lượng");

    txtmapx.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtmapxActionPerformed(evt);
      }
    });

    txtmanv.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtmanvActionPerformed(evt);
      }
    });

    txtsl.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtslActionPerformed(evt);
      }
    });

    txtmasach.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtmasachActionPerformed(evt);
      }
    });

    jLabel7.setFont(new java.awt.Font("Times New Roman", 2, 15)); // NOI18N
    jLabel7.setForeground(new java.awt.Color(255, 255, 255));
    jLabel7.setText("• Ngày lập");

    txtngay.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtngayActionPerformed(evt);
      }
    });

    jLabel8.setFont(new java.awt.Font("Times New Roman", 2, 15)); // NOI18N
    jLabel8.setForeground(new java.awt.Color(255, 255, 255));
    jLabel8.setText("• NCC");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(55, 55, 55)
                        .addComponent(txtngay, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
                            javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtmapx, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
                            javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(22, 22, 22)
                        .addComponent(txtmanv, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
                            javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51,
                    Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                            jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(52, 52, 52))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(txtsoluongxuat)
                            .addGap(48, 48, 48)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(73, 73, 73)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtncc)
                    .addComponent(txtmasach, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsl, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
                        javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)));
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE,
                                39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmapx, javax.swing.GroupLayout.PREFERRED_SIZE,
                                38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE,
                                39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmanv, javax.swing.GroupLayout.PREFERRED_SIZE,
                                38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtmasach, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsl, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsoluongxuat,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 39,
                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout
                    .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtngay, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
                            javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8)
                    .addComponent(txtncc))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

    jButton1.setBackground(new java.awt.Color(0, 102, 51));
    jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
    jButton1.setForeground(new java.awt.Color(255, 255, 255));
    jButton1.setText("Thêm");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    jButton2.setBackground(new java.awt.Color(0, 102, 51));
    jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
    jButton2.setForeground(new java.awt.Color(255, 255, 255));
    jButton2.setText("Xóa");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });

    table_phieuXuat.setModel(new javax.swing.table.DefaultTableModel(
        new Object[][] {

        },
        new String[] {
            "STT", "Mã phiếu", "Mã NV", "Mã NCC", "Mã SGK", "Ngày", "Số lượng"
        }));
    jScrollPane1.setViewportView(table_phieuXuat);

    jButton3.setText("Tìm ");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton3ActionPerformed(evt);
      }
    });

    jButton4.setText("reset");
    jButton4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton4ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(62, 62, 62)
                        .addComponent(jButton2)
                        .addGap(41, 41, 41)
                        .addComponent(jButton4)
                        .addGap(197, 197, 197))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                            javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 129,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)));
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                            javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
  }// </editor-fold>//GEN-END:initComponents

  private void txtmapxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtmapxActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_txtmapxActionPerformed

  private void txtmanvActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtmanvActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_txtmanvActionPerformed

  private void txtslActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtslActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_txtslActionPerformed

  private void txtmasachActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtmasachActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_txtmasachActionPerformed

  private void txtngayActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtngayActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_txtngayActionPerformed

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
    if (txtmapx.getText().equals("")) {
      JOptionPane.showMessageDialog(this, "Nhập mã phiếu cần xóa!");
      txtmapx.requestFocus();
    }
    phieuXuat pn = new phieuXuat();
    pn.setMaPX(txtmapx.getText());

    if (new phieuXuatDAO().delete2(pn)) {
      JOptionPane.showMessageDialog(this, "Xóa thành công! ");
      list = new phieuXuatDAO().getList();
      i = 1;
      loadArray();
    }
  }// GEN-LAST:event_jButton2ActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed

    if (txtmapx.getText().equals("") || txtmanv.getText().equals("") || txtmasach.getText().equals("")
        || txtsl.getText().equals("") || txtncc.getText().equals("")) {
      JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin!");
      return;
    }
    phieuXuat pn = new phieuXuat();
    pn.setMaPX(txtmapx.getText());
    pn.setMaNV(txtmanv.getText());
    pn.setMaNCC(txtncc.getText());
    pn.setMaSGK(txtmasach.getText());
    pn.setNgay(txtngay.getText());
    pn.setSoLuong(Integer.valueOf(txtsl.getText()));

    if (!(txtncc.getText().equals(""))) {
      String mancc = txtncc.getText();
      int n = 0;
      ArrayList<nhaCC> list = new nhaCCDAO().getList();
      for (nhaCC ncc : list) {
        if (mancc.equals(ncc.getMaNhaCC())) {
          n++;
        }
      }
      if (n != 1) {
        JOptionPane.showMessageDialog(this, "Không có mã nhà cung cấp này!");
        return;
      }
    }

    if (!(txtmasach.getText().equals(""))) {
      String mancc = txtmasach.getText();
      int n = 0;
      ArrayList<sachGiaoKhoa> list = new sachGiaoKhoaDAO().getList();
      for (sachGiaoKhoa ncc : list) {
        if (mancc.equals(ncc.getMaSach())) {
          n++;
        }
      }
      if (n != 1) {
        JOptionPane.showMessageDialog(this, "Không có mã sách này!");
        return;
      }
    }

    list.add(pn);
    if (new phieuXuatDAO().insert2(pn)) {
      JOptionPane.showMessageDialog(this, "Add success!");
      i = 1;
      loadArray();

      txtmapx.setText("");
      txtncc.setText("");
      txtmasach.setText("");
      txtsl.setText("");
    } else {
      JOptionPane.showMessageDialog(this, "Mã phiếu không được trùng nhau!");

    }

  }// GEN-LAST:event_jButton1ActionPerformed

  private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
    reset();
  }// GEN-LAST:event_jButton4ActionPerformed

  private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
    Pattern pattern = Pattern.compile("^(0?[1-9]|[12][0-9]|3[01])-(0?[1-9]|1[012])-([12][0-9]{3})$");
    Matcher matcher = pattern.matcher(txtsearch.getText());
    if (matcher.matches()) {
      int n = 0;
      ArrayList<phieuXuat> list2 = new phieuXuatDAO().getList();
      ArrayList<phieuXuat> list3 = new ArrayList<>();
      for (phieuXuat pn : list2) {
        if (pn.getNgay().contains(txtsearch.getText().trim())) {
          list3.add(pn);
          n++;
        }
      }
      if (n == 0) {
        JOptionPane.showMessageDialog(this, "Không tìm thấy!");
      }
      list.clear();
      list.addAll(list3);
      i = 1;
      loadArray();
    } else {
      JOptionPane.showMessageDialog(this, "Không đúng định dạng ngày!");
    }

  }// GEN-LAST:event_jButton3ActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable table_phieuXuat;
  private javax.swing.JTextField txtmanv;
  private javax.swing.JTextField txtmapx;
  private javax.swing.JTextField txtmasach;
  private javax.swing.JTextField txtncc;
  private javax.swing.JTextField txtngay;
  private javax.swing.JTextField txtsearch;
  private javax.swing.JTextField txtsl;
  private javax.swing.JLabel txtsoluongxuat;
  // End of variables declaration//GEN-END:variables
}
